name: "🎨 Art"
description: "New or updated art asset"
type: "feature"
labels: "art"
body:
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: "A clear and concise description of the desired feature/changes."
  validations:
    required: true
- type: checkboxes
  id: scope
  attributes:
    label: "Scope"
    description: "If asset is a 3D model, select what needs to be done."
    options:
      - label: Model
      - label: Sculpting
      - label: Texturing
      - label: Rigging
- type: textarea
  id: additional-context
  attributes:
    label: "Additional context"
    description: "Add any other context about the feature/changes here."
- type: textarea
  id: references
  attributes:
    label: "References"
    description: "Add reference images, if available."
