name: "🦾 Feature"
description: "Feature or improvement on existing functionality"
type: "feature"
body:
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: "A clear and concise description of the desired feature/changes."
  validations:
    required: true
- type: textarea
  id: scope
  attributes:
    label: "Scope"
    description: "Provide some limitations so it's clear when this issue should be considered complete."
- type: textarea
  id: additional-context
  attributes:
    label: "Additional context"
    description: "Add any other context about the feature/changes here."
