name: "🎮🐛 Game Bug"
description: "Report a bug or unexpected in-game behavior"
title: "🎮🐛 "
type: "bug"
labels: "bug"
body:
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: "A clear and concise description of what is wrong."
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: "Expected behavior"
    description: "A clear and concise description of what you expected to happen."
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: "Steps to reproduce"
    description: "A series of steps, detailing how to reproduce the issue."
- type: checkboxes
  id: play-mode
  attributes:
    label: "Mode"
    description: "Which mode did was the issue observed on?"
    options:
      - label: Editor
      - label: Play
      - label: Build
- type: checkboxes
  id: platform
  attributes:
    label: "Platform"
    description: "Which platforms did you test on? Add specifics in \"Additional Content\""
    options:
      - label: Mac
      - label: Windows
      - label: Linux
- type: textarea
  id: additional-context
  attributes:
    label: "Additional context"
    description: "Add any other context about bug."
- type: textarea
  id: screenshots
  attributes:
    label: "Screenshots"
    description: "Add screenshots, if applicable."
