name: "🏗️ Task"
description: "Task that needs to be completed"
title: "[TASK] "
type: "task"
body:
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: "A clear and concise description of what the task is."
  validations:
    required: true
- type: textarea
  id: acceptance-criteria
  attributes:
    label: "Acceptance criteria"
    description: "A list or description of criteria to consider this task complete."
- type: textarea
  id: additional-context
  attributes:
    label: "Additional context"
    description: "Add any other context about bug."
