name: Auto Add Issues to Project
on:
  issues:
    types:
      - opened
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/BloomGameStudio/projects/9
          github-token: ${{ secrets.GITHUB_TOKEN }}
